### ISSUE TITLE
Access denied on Yahoo Quote.  Have they added a crumb here also?

### ISSUE THREAD

**Issue by DonWM** [lppkarl/YahooFinanceApi#10]

**Comment by lppkarl** [comment]
@DonWM Yes. This library also get crumb from yahoo in order to work, but sometimes yahoo just fail to return a crumb or a empty crumb, I have implemented a retry logic on this, hopefully to reduce the chance of getting "Access Denied" error

**Comment by DonWM** [comment]
I didn’t see in your code that you use the crumb for the Quote retrieval – only for the historical.  Have you recently added the crumb to the Quote retrieval?

**Comment by lppkarl** [comment]
@DonWM as far as i know, quote retrieval does not require a crumb to work. I had opened an empty console project and had tried the quote function of the current version (1.0.12) on nuget, the lib just works. I wonder if it's another issue rather than crumb missing. Maybe you could attach the stack trace for me to further investigate the issue?

**Comment by lppkarl** [comment]
This issue has been idled for a month, it will be closed now
