### ISSUE TITLE
Dividend Date

### ISSUE THREAD

**Issue by IvanDuhov** [lppkarl/YahooFinanceApi#46]
Hello guys,

What exactly the Dividend Date should return?

When I get the Dividend Date for MSFT, it returns this: "1591833600".

Thanks for your great work,

Looking forward to answering from you

**Comment by cipher9** [comment]
DividendDate is a Unix timestamp which is the number of seconds elapsed minus leap seconds since 1 January 1970.

The static DateTimeOffset.FromUnixTimeSeconds method converts DividendDate to DateTime format.

Here is an example:
Console.WriteLine($"Dividend Date: {DateTimeOffset.FromUnixTimeSeconds(msft[Field.DividendDate])}");
